apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-deployment.fullname" . }}-mobia-mission-app
  labels:
  {{- include "python-deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mobiaMissionApp.replicas }}
  selector:
    matchLabels:
      app: python-flask
    {{- include "python-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: python-flask
      {{- include "python-deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.mobiaMissionApp.pythonFlaskApp.image.repository }}:{{ .Values.mobiaMissionApp.pythonFlaskApp.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: python-flask-app
        ports:
        - containerPort: 8080
        resources: {}