apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  labels:
    app: python-flask
spec:
  type: LoadBalancer
  selector:
    app: python-flask
  ports:
    - port: 80
      targetPort: 8080