name: Build and Test Artifact

on:
  push:
  pull_request:

env:
  GCP_PROJECT_NAME: mobia-mission
  PROD_NAMESPACE: mobia-prod
  STAGING_NAMESPACE: mobia-staging
  FEATURE_NAMESPACE: mobia-feature
  GKE_CLUSTER_NAME_STAGING: staging
  GKE_CLUSTER_NAME_PROD: prod
  GKE_LOCATION: us-central1
  USE_GKE_GCLOUD_AUTH_PLUGIN: True  


jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install flake8==4.0.1
          pip3 install flake8-html==0.4.1 Jinja2==3.0

      - name: Run linting tests
        run: flake8 --format=html --htmldir=flake8_reports/

      - name: Run linting tests
        run: flake8 --format=html --htmldir=flake8_reports/

      - name: Upload linting reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flake8_reports
          path: flake8_reports/

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install pytest-html
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --html=pytest_reports/pytest-report.html --self-contained-html

      - name: Upload pytest reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest_reports
          path: pytest_reports/