name: Build and Test Artifact

on:
  push:
      branches:
      - 'staging'
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'

env:
  GCP_PROJECT_NAME: mobia-mission
  PROD_NAMESPACE: mobia-prod
  STAGING_NAMESPACE: mobia-staging
  FEATURE_NAMESPACE: mobia-feature
  GKE_CLUSTER_NAME_STAGING: staging
  GKE_CLUSTER_NAME_PROD: prod
  GKE_LOCATION: us-central1
  IMAGE_REPOSITORY: "mobia-mission"
  IMAGE_APP_NAME: "mobia-flask"
  USE_GKE_GCLOUD_AUTH_PLUGIN: True  


jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install flake8==4.0.1
          pip3 install flake8-html==0.4.1 Jinja2==3.0

      - name: Run linting tests
        run: flake8 --format=html --htmldir=flake8_reports/

      - name: Run linting tests
        run: flake8 --format=html --htmldir=flake8_reports/

      - name: Upload linting reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flake8_reports
          path: flake8_reports/

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install pytest-html
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --html=pytest_reports/pytest-report.html --self-contained-html

      - name: Upload pytest reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest_reports
          path: pytest_reports/

  build:
    runs-on: ubuntu-latest
    needs: [lint_test, pytest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Get version SHA
        run: |
          echo "VERSION=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
    
      - name: Build and push API docker image to Google Cloud Platform
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          file: "Dockerfile"
          tags: |
            gcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_APP_NAME }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_feature:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    needs: build
    environment:
      name: feature
    steps:               
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ env.GCP_PROJECT_NAME }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER_NAME_STAGING }}'
          location: 'us-central1'
      - name: Setup helm
        run: |
          chmod +x ./get_helm.sh
          ./get_helm.sh
        shell: bash    
      - name: Get version SHA
        run: |
          echo "VERSION=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
      - name: Authentication with GKE
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME_STAGING }} --region us-central1 --project ${{ env.GCP_PROJECT_NAME }}
          sed -i "s/<VERSION>/${{ env.VERSION }}/g" helm/python-deployment/values.yaml
      - name: Apply helm 
        run: |
          helm upgrade --install python-flask -n ${{ env.FEATURE_NAMESPACE }} helm/python-deployment

  test_feature:
    runs-on: ubuntu-latest
    needs: deploy_feature
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ env.GCP_PROJECT_NAME }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER_NAME_STAGING }}'
          location: 'us-central1'

      - name: Authentication with GKE
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME_STAGING }} --region us-central1 --project ${{ env.GCP_PROJECT_NAME }}
      
      - name: Test feature environment
        run: |
          kubectl get svc -n ${{ env.FEATURE_NAMESPACE }} | awk '{print $4}' | grep -v "EXTERNAL-IP" | while read -r line; do curl "http://$line"; done | grep "Hello Mobia!"

  deploy_stage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    environment:
      name: staging
    steps:               
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ env.GCP_PROJECT_NAME }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER_NAME_STAGING }}'
          location: 'us-central1'
      - name: Setup helm
        run: |
          chmod +x ./get_helm.sh
          ./get_helm.sh
        shell: bash  
      - name: Get version SHA
        run: |
          echo "VERSION=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
      - name: Kubernetes cluster context change
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME_STAGING }} --region us-central1 --project ${{ env.GCP_PROJECT_NAME }}
          sed -i "s/<VERSION>/${{ env.VERSION }}/g" helm/python-deployment/values.yaml
      - name: Apply helm 
        run: |
          helm upgrade --install python-flask -n ${{ env.STAGING_NAMESPACE }} helm/python-deployment


  test_stage:
    runs-on: ubuntu-latest
    needs: deploy_stage
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ env.GCP_PROJECT_NAME }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER_NAME_STAGING }}'
          location: 'us-central1'

      - name: Test staging environment
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME_STAGING }} --region us-central1 --project ${{ env.GCP_PROJECT_NAME }}
          kubectl get svc -n ${{ env.STAGING_NAMESPACE }} | awk '{print $4}' | grep -v "EXTERNAL-IP" | while read -r line; do curl "http://$line"; done | grep "Hello Mobia!"
