name: Teardown Feature Application

on:
  workflow_dispatch:

env:
  GCP_PROJECT_NAME: mobia-mission
  FEATURE_NAMESPACE: mobia-feature
  GKE_CLUSTER_NAME_STAGING: staging
  IMAGE_REPOSITORY: "mobia-mission"
  IMAGE_APP_NAME: "mobia-flask"
  GKE_LOCATION: us-central1
  USE_GKE_GCLOUD_AUTH_PLUGIN: True  


jobs:
  stop_feature:
    runs-on: ubuntu-latest
    environment:
      name: feature/$GITHUB_REF_SLUG
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ env.GCP_PROJECT_NAME }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER_NAME_STAGING }}'
          location: 'us-central1'
      - name: Setup helm
        run: |
          chmod +x ./get_helm.sh
          ./get_helm.sh
        shell: bash    
      - name: Authentication with GKE
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME_STAGING }} --region us-central1 --project ${{ env.GCP_PROJECT_NAME }}
      - name: Stop feature environment
        run: |
          helm uninstall python-flask -n ${{ env.FEATURE_NAMESPACE }}
